version: 0.2

phases:
  install:
    commands:
      - echo Login to Docker hub
      - echo "${DOCKERHUB_PASSWORD}" 
      - echo "${DOCKERHUB_USERNAME}" 
      - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 921975613299.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_REPO_NAME = gnmn
      - REPOSITORY_URI=921975613299.dkr.ecr.us-east-1.amazonaws.com/gnmn
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing definitions file...